name: Generate documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        
      # Using this approach to make it easier to integrate with cmake        
      - name: Run doxygen
        run: |
          if [ ! -d build ]; then mkdir build; fi
          cd build
          doxygen ../Doxyfile.ini
          
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Update documentation for commit {sha}
